### ISSUE TITLE
Type aliases isn't supported yet?

### ISSUE THREAD

**Issue by AlesTsurko** [dtolnay/cxx#100]
`intptr_t` from libc is an alias for `isize` (https://docs.rs/libc/0.2.68/libc/type.intptr_t.html), but when I use `libc::intptr_t` inside **extern "Rust"** block, I get the `unsupported type` error. When I change it to `isize`, keeping `intptr_t` outside the block (i.e. in the function declaration), it works.

**Comment by dtolnay** [comment]
This is intentional -- determining that the name `intptr_t` in your program refers to the same type as `isize` requires typechecking your program. That would mean we would need to wait until after your Rust code is done compiling before we could generate the correct C++ code and begin compiling it. Instead by doing the C++ code generation purely syntactically without Rust type information it's possible for the Rust and C++ side to compile in parallel.

**Comment by AlesTsurko** [comment]
Got it. Thanks for the explanation.
