### ISSUE TITLE
Symbolic link targeting an ancestor directory

### ISSUE THREAD

**Issue by Geobert** [dtolnay/cxx#1004]
Hi,

we discover some weird directory tree pattern in the build of a cxx bridge:

> $ find . -follow -name foo
> find: File system loop detected; './our_crate/target/debug/build/our_crate-1356a31d58aae0f3/out/cxxbridge/crate/our_crate' is part of the same file system loop as './our_crate'.

Because:

> $ ls -ld ./our_crate/target/debug/build/our_crate-1356a31d58aae0f3/out/cxxbridge/crate/our_crate
> lrwxrwxrwx 1 dbw users 59 Jan 25 15:10 ./our_crate/target/debug/build/our_crate-1356a31d58aae0f3/out/cxxbridge/crate/our_crate -> /dsk/hostname/username/Git/build/company_name/src/apps/our_crate

It seems odd to have a symbolic link pointing to an ancestor of the link.

**Comment by dtolnay** [comment]
This is intentional, what you are seeing is the include path give to the C++ compiler so that it understands what to do with `#include "our_crate/path/to/header.h"`.

If you need those links to not be placed inside of the crate's source directory (which is Cargo's default) then you can make Cargo put the whole targets dir somewhere else by building with `CARGO_TARGET_DIR=/path/to/somewhere/else`.

**Comment by casimcdaniels** [comment]
@dtolnay Would it not be possible to simply copy the files instead of recursively symlinking?

**Comment by wravery** [comment]
I had a similar issue where my build system didn't cache the outputs of my cargo build, even with an out-of-source build directory, due to what it called a "reparse" point from the symlink back to the source directory.

I realized those symlinks are not needed after the `cc` build is done. I've only used this on Windows, and it's potentially destructive so make sure you have everything in source control before you use it, but I just put a call to this function in my build script after each `compile("lib_name")` call, parameterized on the crate directory name:

```rust
use std::env;
use std::fs::remove_dir;
use std::path::PathBuf;

pub fn clean_symlinks(crate_name: &str) {
    let out_dir = env::var("OUT_DIR").unwrap();
    let mut crate_dir = PathBuf::from(&out_dir);
    crate_dir.push("cxxbridge");
    crate_dir.push("crate");
    crate_dir.push(crate_name);
    remove_dir(crate_dir).expect("failed to remove the symlink created by cxx");
}
```

There's code in this repo which cleans up the symlinks in preparation for creating new ones, and it has lots of platform checks and some branches on Windows depending on the target (file or directory) of the symlink. Like I said, I've only use this on Windows, and I know the target of the symlink is a directory, so this is simplified for my use case. I recommend looking at [best_effort_remove](https://github.com/dtolnay/cxx/blob/f1c65108ceb7cc734fd40153ff6568c91a524e39/gen/build/src/out.rs#L86) if you need to handle anything more complicated.

**Comment by wravery** [comment]
...and yes, this is a total hack that's coupled to an implementation detail of this crate at this specific version. 😄 No warrantee is expressed or implied.
