### ISSUE TITLE
Define shared struct in separate file 

### ISSUE THREAD

**Issue by ShayMusachanov-dev** [dtolnay/cxx#1077]
Hello to everybody. Is it possible to define shared structs in a separate file?

**Use case:**
I have generated Rust structs from a Protobuf definition and would like to expose them as shared structs in my bridge definition.
From what I can tell, the fields on the generated structs are supported (except Option<T>, but I saw its WIP). 
As a workaround, I tried to use the include! Macro in the bridge definition, Unfortunately, it doesn't work.

**another question**
Until the Option enum becomes supported, is there a temporary solution I can use to move Option in a shared struct?

**Comment by casimcdaniels** [comment]
We ran into this issue as well. We opted to declare the bridge as communicating with raw bytes and do deserialization/serialization on the C++ side of the boundary instead of trying to pass around the types through the bridge. Since you're using protobuf, this should be relatively straightforward as you can also generate your C++ from your schema. It's a lot less work than trying to manually write bridge code.

**Comment by dtolnay** [comment]
A bridge using types from another module (or even another crate), whether shared structs or anything else, is already supported. It looks something like this:

```rust
// src/main.rs

mod common;

#[cxx::bridge]
pub mod ffi {
    extern "C++" {
        include!("example/src/common.rs.h");

        type MyStruct = crate::common::MyStruct;
        type Thing = crate::common::Thing;
    }

    unsafe extern "C++" {
        include!("example/include/header.h");

        fn demo(thing: Thing) -> MyStruct;
    }
}

fn main() {
    let thing = ffi::Thing { is: true };
    println!("{:?}", ffi::demo(thing));
}
```

```rust
// src/common.rs

pub use ffi::*;

#[cxx::bridge]
mod ffi {
    #[derive(Debug)]
    struct MyStruct {
        things: Vec<Thing>,
    }

    #[derive(Debug)]
    struct Thing {
        is: bool,
    }
}
```

```cpp
// include/header.h

#pragma once
#include "example/src/common.rs.h"

static MyStruct demo(Thing thing) {
  MyStruct my;
  my.things.push_back(thing);
  return my;
}
```

**Comment by casimcdaniels** [comment]
> A bridge using types from another module (or even another crate), whether shared structs or anything else, is already supported. It looks something like this:
> 
> ```rust
> // src/main.rs
> 
> mod common;
> 
> #[cxx::bridge]
> pub mod ffi {
>     extern "C++" {
>         include!("example/src/common.rs.h");
> 
>         type MyStruct = crate::common::MyStruct;
>         type Thing = crate::common::Thing;
>     }
> 
>     unsafe extern "C++" {
>         include!("example/include/header.h");
> 
>         fn demo(thing: Thing) -> MyStruct;
>     }
> }
> 
> fn main() {
>     let thing = ffi::Thing { is: true };
>     println!("{:?}", ffi::demo(thing));
> }
> ```
> 
> ```rust
> // src/common.rs
> 
> pub use ffi::*;
> 
> #[cxx::bridge]
> mod ffi {
>     #[derive(Debug)]
>     struct MyStruct {
>         things: Vec<Thing>,
>     }
> 
>     #[derive(Debug)]
>     struct Thing {
>         is: bool,
>     }
> }
> ```
> 
> ```c++
> // include/header.h
> 
> #pragma once
> #include "example/src/common.rs.h"
> 
> static MyStruct demo(Thing thing) {
>   MyStruct my;
>   my.things.push_back(thing);
>   return my;
> }
> ```

I think they mean they already have struct definitions outside of his cxx crate (protobuf generated rust structs) that they want to reuse in the bridge. This is most definitely not supported. The cxx crate currently only supports shared structs that are defined within a bridge module and does not let you use types defined outside of a bridged mod

**Comment by dtolnay** [comment]
If so, that is also supported, using an [ExternType](https://docs.rs/cxx/1.0.80/cxx/trait.ExternType.html) impl.

Ultimately one of the following is always true, which are all supported:

- You put cxx in charge of producing an ABI-compatible C++ type definition; this is what "shared struct" means. My previous comment does this.

- You supply the ABI-compatible C++ definition of a Rust struct or vice versa. This is a handwritten `ExternType` impl.

- There is no need for an ABI-compatible C++ definition. This is "opaque Rust type" in https://cxx.rs/extern-rust.html#opaque-rust-types.

**Comment by casimcdaniels** [comment]
> * You put cxx in charge of producing an ABI-compatible C++ type definition; this is what "shared struct" means. My previous comment does this.

@dtolnay Right, so it seems this to work only with types that are defined inside of a cxxbridge module. I've tried the following:

Given the existing rust type:

```rust
// types.rs

pub struct Message {
   msg: String
}
```

And then in the CXX Bridge

```rust

[#cxx::bridge]
mod ffi {
  type Message = crate::types::Message
}
```

Or 

```rust

[#cxx::bridge]
mod ffi {
  struct Message(crate::types::Message)
}
```

Or 

```rust

[#cxx::bridge]
mod ffi {
  struct Message {
      inner: crate::types::Message
  }
}
```

**Comment by casimcdaniels** [comment]
https://github.com/dtolnay/cxx/issues/670 covers the exact problem here.

**Comment by dtolnay** [comment]
You wrote some things that indicate you haven't grappled with the fundamental question in https://github.com/dtolnay/cxx/issues/1077#issuecomment-1301464361. Are you interested in the necessary ABI-compatible C++ type definition to be produced by cxx, to be written by the programmer, or to not exist / the type manipulations on the C++ side be runtime-only ("dynamically sized"). If the first, obviously cxx would need to know the complete Rust definition of the relevant type, which you haven't reflected above.

**Comment by casimcdaniels** [comment]
I'm speaking in place of @ShayMusachanov-dev here so please chime in if I'm misinterpreting completely. The fundamental question seems to be this from my perspective:

My assumptions:
- They do not want to generate their protobufs into a mod annotated with `#[cxx::bridge]`
- They do not want to write matching types for C++ and instead lean on CXX to generate the C++ side of things using shared structs
- They do not want to rewrite their protobuf model structs inside of a cxxbridge and instead reuse them (if possible)
- They do not want opaque types so they can access fields populated on the Rust side from the consuming C++ code.

The problem:

- They are using a proto gen crate to produce a Rust library that has generated types from their .proto schema. Not sure what library they are using, but the output will be some standard rust structs with helper funcs such as in [this generated example](https://github.com/tafia/quick-protobuf/blob/master/quick-protobuf/examples/pb_rs/data_types.rs)
- They would like to reuse their generated types as a shared struct (I personally don't think they need to share these types across the bridge in the first place with protobuf already being a multi-language solution, but the point still stands for non-protobuf usecases)
- Since the struct needs to be declared inside a `#[cxx::bridge]` annotated mod in order for it to be considered a **shared struct** and because shared structs don't allow for reusing types _not defined_ in some  `#[cxx::bridge]` mod, they cannot simply re-use their types by doing something like:

```rust
#[cxx::bridge]
mod ffi {
  type MyMessageTypeFromProtobuf = crate::proto::gen::MyMessageTypeFromProtobuf
}
```

I'm assuming this is because the CXX macro has no way of understanding what fields exist on `crate::proto::gen::MyMessageTypeFromProtobuf` and so it's unable to generate a C++ representation from a type alias.

**Comment by dtolnay** [comment]
I guess I would just say that "I'm thinking of a type; I won't tell you what type it is but I want you to generate a compatible C++ definition for it" is not a use case that is supported by this library, because it is envisioned as being a C++ interop library, and not a mind-reading library. So, subject to that, it would be up to the programmer how to make that not the thing they are asking for.

For example, anyone could write a tool to parse a protobuf-generated module (or an arbitrary module I guess) and spit out correct `ExternType` impls for all its types by turning:

```rust
pub struct BarMessage { // from your link
    pub b_required_int32: i32,
}
```

into:

```rust
// generated.rs
use cxx::{type_id, ExternType};

unsafe impl ExternType for crate::BarMessage {
    type Id = <private::BarMessage as ExternType>::Id;
    type Kind = <private::BarMessage as ExternType>::Kind;
}

#[cxx::bridge]
#[namespace = "whatever you want"]
mod private {
    struct BarMessage { // distinct from crate::BarMessage, but matching layout
        b_required_int32: i32,
    }
}
```

With this you could run cxx-build on generated.rs from build.rs to make the bridge's C++ side, and `include!` generated.rs from lib.rs to make the Rust side.

**Comment by maaft** [comment]
@casimcdaniels did you find any crate that lifts the duplication stuff for us?
