### ISSUE TITLE
c++ bridge as static library

### ISSUE THREAD

**Issue by fgadaleta** [dtolnay/cxx#1108]
Is it possible to compile the c++ bridge (that in turn performs calls to the Rust backend), as a static library, such that a c++ developer would just include (from where?) and ready to extend her program with Rust functionality?

**Comment by dtolnay** [comment]
Yes, this is pretty much always how it would be compiled.

https://cxx.rs/build/other.html briefly discusses `staticlib` linkage.

**Comment by Jashwanth537** [comment]
Hi @dtolnay can you please share some demo example for the same, i did try out as per docs but run into a bunch of linker errors which i'm unable to debug. Any help would be so grateful.

**Comment by Keeyuu** [comment]
@dtolnay I still don't understand this. My requirement is to use rust to write something for C++, compile rust into a static library, and then embed it into C++ project. I don't know if cxx can meet my needs, instead of building it together in cargo. What rust does is just build static libraries and have some convenient C++ bridge conversion.
