### ISSUE TITLE
Please ensure that third-party/Cargo.lock is updated before releases

### ISSUE THREAD

**Issue by daira** [dtolnay/cxx#1157]
Not doing so makes it more difficult to use cxx in projects that require pinning and auditing of all dependencies for security reasons (see https://github.com/zcash/zcash/pull/6364#discussion_r1084741751 and https://github.com/zcash/zcash/pull/6364#issuecomment-1401312202).

(Ideally, update `third-party/Cargo.lock` now and do a release, as well as ensuring this is done for future releases.)

**Comment by dtolnay** [comment]
I have to say I don't understand what this issue is asking. I read the linked PR too which says _"the lockfile was updated just before the version bump, so it was correct except for the version of cxx itself"_. However there isn't a version of cxx in the lockfile in the first place, since this repo uses it for locking the vendored third-party deps only. So I'm not seeing the way that it would have been out of date.

**Comment by str4d** [comment]
The third-party deps lockfile _did_ previously include the `cxx` version, and was included in crate release version bumps:

https://github.com/dtolnay/cxx/commit/340f0ba52ac4086ee1fdd0c251dc3d4874043a53#diff-3d71a20e095c48e62d8dbc74d1a3dc4da4ddd6e2a9a9c3fea4f910243ff3e363

Some context: We pin and build `cxxbridge` downstream in our dependency system, and (for deterministic build reasons) need to build it with `--locked`. Previously we maintained our own `Cargo.lock` for this, but then discovered `third-party/Cargo.lock` which was being included in published release tarballs, and so we believed this was the set of dependencies that `cxx` was intended to be built against. This worked fine for release tarballs up to 1.0.83.

Something changed in 1.0.84 that caused `third-party/Cargo.lock` to no longer be generated in the context of building `cxx`. Was this intentional? And if so, what is the intended usage of this lockfile?

**Comment by str4d** [comment]
I did some git digging, and it looks like https://github.com/dtolnay/cxx/pull/1141 is the cause of this change to the release tarball. So I guess this means downstream users of `cxx` should _not_ interpret `third-party/Cargo.lock` as the committed lockfile for the application components of `cxx` such as `cxxbridge`, given that it is now unusable for `cargo build --locked`?
