### ISSUE TITLE
How should `third-party/Cargo.lock` in release tarballs be interpreted by downstream users?

### ISSUE THREAD

**Issue by str4d** [dtolnay/cxx#1173]
In release tarballs up to 1.0.83, the third-party deps lockfile at `third-party/Cargo.lock` included the `cxx` version, and was included in crate release version bumps:

https://github.com/dtolnay/cxx/commit/340f0ba52ac4086ee1fdd0c251dc3d4874043a53#diff-3d71a20e095c48e62d8dbc74d1a3dc4da4ddd6e2a9a9c3fea4f910243ff3e363

From 1.0.84, `third-party/Cargo.lock` is no longer generated in the context of building `cxx`, due to changes in https://github.com/dtolnay/cxx/pull/1141. This means downstream users of `cxx` cannot use  `third-party/Cargo.lock` to build with `cargo build --locked`.

How should `third-party/Cargo.lock` be interpreted? Is it meant to be the committed lockfile for the application components of `cxx` such as `cxxbridge`? And if so, can we ensure that it is usable as such?

**Comment by dtolnay** [comment]
It is not meant to be the committed lockfile for the application components of `cxx` such as `cxxbridge`.

**Comment by dtolnay** [comment]
To elaborate slightly more: I said this already in #1157 but the file you are fixated on is something used for generating the build targets which are part of this repo's Buck and Bazel-based test suite. I don't know of any documentation that would have directed you to use it for a different purpose.

Separately, the thing you are calling "release tarball" is not a release tarball but a snapshot of the git repository generated automatically by GitHub. You can obtain a "release tarball" of any arbitrary commit of any repo; it is not particular to releases. Those tars reflects whatever contents are in the repo. It is not correct to expect that whatever can be found in a tarball must have been placed there with the intention of having some intended purpose outside of the source repo. Test suites, websites, graphics, etc would all be found in there. If it's in the repo, it's in GitHub's generated tars of the repo. Notably, this is a different thing than rust-lang/rust's `rust-src` rustup component, for example, which is a release tarball.

In general the norm for lockfiles in Rust is to provide them for applications only. The `cxxbridge-cmd` crate is not an application. It is a dependency which you would use at build time for building some application. Dependencies which are used at build time for building an application (including libraries, build scripts, proc macros, etc) are not supposed to have each their own unique lockfile. For example the `serde` crate, or `serde_derive`, or `cxx`, or `cxxbridge-cmd`, would be governed by the lockfile of whatever application whose build they are a part of. This is important because you want sharing of the common dependency graph between different dependencies of an application's build. For example if `serde_derive` and `cxx` and `cxxbridge-cmd` all depend on some crate like `syn`, the one version of `syn` in that application's lockfile is the one that all of those dependencies would optimally be built against. It does not make sense for each such crate to have a different lockfile all out of sync with one another.

**Comment by str4d** [comment]
> The `cxxbridge-cmd` crate is not an application.

This confuses me, because we are literally building a `cxxbridge` binary? And it is not possible (without very invasive and customised hooking that would likely break across `cxx` releases) to build this binary using the same `Cargo.lock` file as the Rust components of our hybrid application, because the binary is defined in the `cxxbridge` crate, not our workspace.

> It is a dependency which you would use at build time for building some application. Dependencies which are used at build time for building an application (including libraries, build scripts, proc macros, etc) are not supposed to have each their own unique lockfile. For example the `serde` crate, or `serde_derive`, or `cxx`, or `cxxbridge-cmd`, would be governed by the lockfile of whatever application whose build they are a part of.

Indeed, when `cxx-build` is used inside the `build.rs` file of a Cargo-led build process, then it is used as a _library_, and its dependencies are pinned to the application's `Cargo.lock`. But an automake-led build process needs to use the `cxxbridge` _binary_ [as documented here](https://cxx.rs/build/other.html#producing-the-generated-code), and that binary needs to be built with its own `Cargo.lock` file.

In any case, this answer sufficiently clarifies your position:

> It is not meant to be the committed lockfile for the application components of `cxx` such as `cxxbridge`.

and tells me that we need to go back to our original approach of checking in two separate `Cargo.lock` files (one for our workspace, and one specifically for `cxxbridge`), and updating both of them every time we update `cxx` in any way.

**Comment by dtolnay** [comment]
I believe you are conflating "application" with `--crate-type=bin`. The latter is something more general / a superset of the former. Something being built as a binary (crate type) during a build does not make it what is ordinarily meant by application.

For example `serde`'s or `cxx`'s build script are also binaries. You can confirm this by running a `cargo build --verbose` on anything which depends on those libraries. The build scripts do not come with their own lockfile. They are nevertheless built using `--crate-type=bin`, which is no different from how a proper build system would be expected to integrate `cxxbridge-cmd` and any other code generators relevant to a build.

**Comment by str4d** [comment]
> The build scripts do not come with their own lockfile.

Indeed, because a Cargo build script is not "standalone"; it is a sub-component of the Rust crate being built, that happens to be compiled as a binary and run as a sub-task by `cargo`. That is an artifact of how Cargo works, and is how it can share a `Cargo.lock` file. This is **not possible** for a binary built from a different `Cargo.toml`, as described below.

---

[The `cxx` documentation](https://cxx.rs/build/other.html#producing-the-generated-code), which is what I referenced when integrating it into our automake build system (about as proper as one gets for a legacy C++ application), states (emphasis added):

> ### Producing the generated code
>
> CXX's Rust code generation automatically happens when the `#[cxx::bridge]` procedural macro is expanded during the normal Rust compilation process, so no special build steps are required there.
>
> But the C++ side of the bindings needs to be generated. Your options are:
> - Use the `cxxbridge` command, which is a **standalone** command line interface to the CXX C++ code generator. Wire up your build system to **compile and invoke this tool**. [... It] can be built from the `gen/cmd/` directory of the CXX GitHub repo.

This is precisely what we are doing. The build system runs:

```bash
[make -C depends, which runs]
cd gen/cmd && cargo build --locked --offline --release --package=cxxbridge-cmd --bin=cxxbridge

[remainder of dependencies are built]

[./configure]

[make, which runs]
...
path/to/cxxbridge $(CXXBRIDGE_OPTS) rust/src/$(basename $(@F)).rs -o $@
...
cargo build --manifest-path path/to/our/Cargo.toml
...
```

`cxxbridge` is being built by a different `cargo build` invocation than our Rust library, using a different `Cargo.toml` file (specifically, the one from this repository at `gen/cmd/Cargo.toml`). And (I know you are a long-time core contributor to the Rust ecosystem, so you already know this, but stating it for completeness) a `Cargo.lock` file is always defined relative to a given `Cargo.toml` file(-state). This means that:

**`cxxbridge` does not, and cannot, use the same `Cargo.lock` file as our Rust library.**

If I attempt to do so, I get the following error:
```bash
$ tar xzf cxx-1.0.83.tar.gz
$ cp path/to/our/repository/Cargo.lock cxx-1.0.83/Cargo.lock
$ cd cxx-1.0.83/gen/cmd
$ cargo build --locked --offline --release --package=cxxbridge-cmd 
error: the lock file path/to/cxx-1.0.83/Cargo.lock needs to be updated but --locked was passed to prevent this
If you want to try to generate the lock file without accessing the network, remove the --locked flag and use --offline instead.
```

As noted in #1157, we cannot build without `--locked` for reproducibility reasons; specifically the build needs to work in an offline deterministic VM environment with vendored dependencies. And because `cxxbridge` is built by a different `cargo build` invocation and using a different `Cargo.toml`, it has a different set of dependencies, only a subset of which are in common with our Rust library.

There are hacks I could use to get around this, but (in addition to breaking several boundary abstractions within our build system) they are semantically eqivalent to "just ship our own `Cargo.lock` file for `cxxbridge` that we bump on updates, instead of depending on one provided by the `cxx` repo".

---

Hopefully this makes it clear that there exists an impedance mismatch between your intentions for how `cxxbridge` should be used, and how downstream people like myself actually use it based on reading the `cxx` documentation and looking at the repository contents. Hopefully you can use this information to improve the `cxx` documentation for future users. But I have now spent over an hour of my life in this issue thread, have run out of spoons trying to convey my downstream user experience to you, and am unable to continue this conversation.

**Comment by str4d** [comment]
One last follow-up for the benefit of others who might find this issue: I just now learned about [RFC 3028: `cargo` binary dependencies](https://rust-lang.github.io/rfcs/3028-cargo-binary-dependencies.html) which _would_ AFAICT allow a binary build tool to be tracked as a dependency in a project's `Cargo.toml` and built by it, therefore sharing its `Cargo.lock` file. This further supporting my understanding that right now this is not possible.
