### ISSUE TITLE
Represent enums using the smallest sufficient integer type

### ISSUE THREAD

**Issue by dtolnay** [dtolnay/cxx#175]
The C-style enum support added in #170 unconditionally uses `u32` / `uint32_t` as the representation. However, this means a negative discriminant like `-1` or a large discriminant like `0xfffffffff` won't compile. Additionally, an explicitly typed discriminant literal like `0u8` just ignores the type.

It would be nice to infer the intended discriminant type from the values. For example:

- If the discriminants are `0`, `1`, `2` -> `u8`
- If they are `-1`, `0`, `1` -> `i8`
- If they are `0u16`, `1`, `2` -> `u16`

**Comment by jgalenson** [comment]
I would add to this that we should be able to specify the integer type so that we can match an existing C++ enum.

**Comment by dtolnay** [comment]
Specifying the integer type is shown in my third bullet, where the discriminant is written as `0u16` so the representation is decided as `u16`.

Interop with an existing C++ enum is tracked separately by #177.

**Comment by jgalenson** [comment]
I was thinking more along the lines of allowing users to annotate the enum with "#[repr(u8)]" or whatever and use that when available.  This seems to me to be an easier way to force the type to be something specific than forcing users to set discriminant values.

This does overlap with #177, but I'm mentioning it here because I feel like it should override what you're suggesting here.

**Comment by dtolnay** [comment]
:+1: I am on board with recognizing #\[repr(u8)\].
