### ISSUE TITLE
How to reference fns with __

### ISSUE THREAD

**Issue by blainekasten** [dtolnay/cxx#211]
Hey there!

Loving this library. Lightyears better than bindgen. One of the problems I'm currently running into is figuring out how to properly build my c interface. This is my [.h file](https://github.com/xiph/flac/blob/master/src/flac/encode.h#L115) and the exported name is `flac__encode_file`, when I try to use that identifier cxx tells me that double underscores are reserved [(which looks like it's happening here)](https://github.com/dtolnay/cxx/blob/master/syntax/ident.rs#L11-L13). 

I'm curious if you know the proper way to link to this method. I've tried using namespacing but nothing is really working.

I'm also academically curious why we would even need to restrict double underscores. I'm not a c developer, so I don't have a lot of context around this.

**Comment by dtolnay** [comment]
I reserved `__` for now just to carve out a space of Rust function names that we can use for implementation details without worrying about collision with user-controlled names. For example [these names](https://github.com/dtolnay/cxx/blob/57d3c68a23833dde3fc86734fefdb5476a539fa8/macro/src/expand.rs#L607-L609) make use of it. I expect to relax it shortly but it just needs some attention to how we name internal identifiers.

For now, a workaround would be to reexport those functions under a different name by adding a header that has:

```cpp
namespace flac_ffi {
int encode_file(...) {
  return ::flac__encode_file(...);
}
}
```

and then writing the binding against flac_ffi::encode_file instead of flac__encode_file.

**Comment by blainekasten** [comment]
@dtolnay Thanks so much for the reasoning and advice. This will def help unblock me! ❤️
