### ISSUE TITLE
UniquePtr<CxxVector<T>> issue

### ISSUE THREAD

**Issue by alexxbb** [dtolnay/cxx#225]
```rust
#[cxx::bridge]
pub(crate) mod ffi {
    extern "C" {
        include!("cpp/wrap/vnp3-rs.h");
        pub type Spref;
        pub type Product;
        pub type Version;
        pub fn new_spref(n: &str) -> UniquePtr<Spref>;
        pub fn get_location(spref: &Spref) -> String;
        pub fn new_product_from_spref(spref: &Spref) -> UniquePtr<Product>;
        pub fn product_get_versions(spref: &Product) -> UniquePtr<CxxVector<Version>>;
    }
}

pub struct Spref {
    ptr: UniquePtr<ffi::Spref>
}

pub struct Product {
    ptr: UniquePtr<ffi::Product>
}

pub struct Version {
    ptr: UniquePtr<ffi::Version>
}
```

```
error[E0277]: the trait bound `ffi::Version: cxx::unique_ptr::UniquePtrTarget` is not satisfied
  --> src/lib.rs:27:5
   |
27 |     ptr: UniquePtr<ffi::Version>
   |     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^ the trait `cxx::unique_ptr::UniquePtrTarget` is not implemented for `ffi::Version`
   |
   = note: required by `cxx::unique_ptr::UniquePtr`

error: aborting due to previous error
```
On the c++ side `Product` and `Version` are very similar and simple classes, but 
```rust
pub struct Product {
    ptr: UniquePtr<ffi::Product>
}
``` 
works fine while 

```rust
pub struct Version {
    ptr: UniquePtr<ffi::Version>
}
``` 
gives me that error.

There are related closed issues #67 and #33. Any idea why?

**Comment by dtolnay** [comment]
Right now we don't support instantiating UniquePtr\<T\> with arbitrary types T -- because e.g. UniquePtr::from_raw requires something to have generated the right small C++ function for that construction to delegate to. So UniquePtr\<T\> will only work for type T where `cxx` "knows about" your usage of UniquePtr\<T\>. For now that means only when UniquePtr\<T\> appears in one of your FFI signatures.

The reason you saw `UniquePtr<ffi::Product>` work but `UniquePtr<ffi::Version>` not work is because `mod ffi` contains a `UniquePtr<Product>` but not a `UniquePtr<Version>`; so the C++ snippets required to make UniquePtr\<Version\> work have not been generated.

For now a less-than-great workaround is to add a new (unused) function to your ffi module whose signature contains a `UniquePtr<Version>` (doesn't matter if argument or return value).

Longer term I want a more satisfactory solution here, maybe by implementing cxx::UniquePtr in Rust in a more intelligent way to support arbitrary T, or maybe instead by an attribute of some sort to inform `cxx` about your plan to use UniquePtr with a particular type, such as maybe like this:

```rust
extern "C" {
    #[generate(UniquePtr)]
    pub type Version;
}
```

**Comment by alexxbb** [comment]
I see. Thx @dtolnay, creating a stub function with a proper signature does the job! 
Now, looks like CxxVector doesn't implement Deref to a slice. Would it be possible to implement this in cxx?

P.S. I know std::shared_ptr is not implemented yet, and the library I'm trying to wrap is heavy on shared pointers, looking forward to seeing this implemented.

**Comment by dtolnay** [comment]
Yeah we should add Deref. As you noticed, the vector APIs (both rust::Vec in C++ and cxx::CxxVector in Rust) are currently bare bones only.

Deref isn't 100% straightforward because I think C++ does not have anything analogous to deref for empty vector. It provides `begin()` but turning that into a memory address requires it to point to an actual vector element rather than past-the-end. Implementing Deref as `ptr=&*v.begin(), len=v.size()` would be undefined behavior on empty vectors. That means we'll need our own extra runtime check in there: `if (size == 0) { ptr = reinterpret_cast<T*>(alignof(T)); } else { ptr = &*v.begin(); }`.

**Comment by alexxbb** [comment]
Got it. Personally I'd choose more features and convenience over a potential few % performance loss in runtime checks at this time.

Cheers.
