### ISSUE TITLE
Shared Type Question

### ISSUE THREAD

**Issue by scott-wilson** [dtolnay/cxx#330]
Hey, this may not be the right direction to go, but feel free to correct me.

I am wrapping a C++ library, and they've defined a struct like this:

```cpp
struct Thing {
    unsigned char someenum;
}
```

I want to be able to directly access the struct with a Rust struct like this:

```rust
enum SomeEnum {
    A,
    B,
    C
}
struct Thing {
    someenum: SomeEnum,
}
```

As a test, I've tried doing something like this:

```rust
#[cxx::bridge]
mod ffi {
    enum SomeEnum {
        A,
        B,
        C,
    }

    struct Thing {
        someenum: SomeEnum,
    }
}

unsafe impl cxx::ExternType for ffi::Thing {
    type Id = cxx::type_id!("Thing");
}
```

But I'm probably misunderstanding how ExternType works.

Either way, is this (or something like this) possible to do in cxx currently (or will be possible in the near future)?

Thanks!

**Comment by dtolnay** [comment]
Shared structs produce both a Rust definition and a C++ definition. If a C++ definition already exists, you can't use a shared struct for the same thing, but you can use an extern C++ type.

```rust
#[repr(u8)]
pub enum SomeEnum {
    A,
    B,
    C,
}

#[repr(C)]
pub struct Thing {
    someenum: SomeEnum,
}

unsafe impl cxx::ExternType for Thing {
    type Id = cxx::type_id!("Thing");
}

#[cxx::bridge]
mod ffi {
    extern "C" {
        type Thing = crate::Thing;
    }
}
```

**Comment by dtolnay** [comment]
That is a rustfmt bug https://github.com/rust-lang/rustfmt/issues/4159 which was fixed in https://github.com/rust-lang/rustfmt/pull/4164 but has not been released yet (:slightly_frowning_face: for a long time). I've opened https://github.com/rust-lang/rustfmt/pull/4447 to backport the fix to the current released version of rustfmt.

For now you can either switch to rustfmt v2.0.0-rc.2 which contains the fix, or use #\[rustfmt::skip\].

**Comment by scott-wilson** [comment]
I'll use the skip. Thanks!
