### ISSUE TITLE
Is C++11 the minimum supported C++ version?

### ISSUE THREAD

**Issue by david-cattermole** [dtolnay/cxx#435]
Hello David,

In the README.md C++11 is stated as the minimum supported C++ version, however the generated C++ code uses `std::make_unique` which is a C++14 feature. 

My project must target C++11 for compatibility reasons, so I have added a small `std::make_unique` implementation to allow me to compile under C++11.
https://github.com/david-cattermole/cxx-demo-example/blob/main/include/mmscenegraph.h#L16

I am using GCC 6.3.1 under CentOS 7.x, with Red Hat Developer Toolset 6.

Is C++14 the true minimum version? 
Is there anything we can do to make C++11 also supported?

Thanks,
David Cattermole

**Comment by dtolnay** [comment]
Correct, C++11 is the minimum supported version. The generated code *does not* use make_unique.

**Comment by david-cattermole** [comment]
I see my mistake now.

I have copied your demo, but your demo uses `std::make_unique`.
https://github.com/dtolnay/cxx/blob/master/demo/src/demo.cc#L13

Would you be open to PR to change the demo to be compatible with C++11?
Or perhaps I could simply add a comment explaining that the demo's minimum C++ version is C++14?

Thanks for such a fast reply.
David

**Comment by dtolnay** [comment]
I think I would prefer to leave this as is. It should be no question that the user's code is allowed to use features from a newer standard (though obviously is not required to). For the cxx-demo-example repo, since it's your own part of the code containing the make_unique call (https://github.com/david-cattermole/cxx-demo-example/blob/c33d50b4aaa1e7638ce4b62e955e620a458a64e0/src/lib.cpp), I would recommend replacing that one make_unique rather than adding a make_unique impl in mmscenegraph.h.

**Comment by david-cattermole** [comment]
Thank you! 
I've taken your recommendation and removed my implementation of `make_unique`.
Everything is fine now.
