### ISSUE TITLE
Building a staticlib that includes a C library dependency.

### ISSUE THREAD

**Issue by mindv0rtex** [dtolnay/cxx#545]
This may not be an issue with `cxx` per se, so feel free to close this issue if so. Let me describe my situation.

You may remember I opened an issue earlier about building a library from `cxx` that I would then link in my C++ project via CMake. You said that in this case I need to build it as a `staticlib` crate type, which works great. The only problem with this is that my Rust code has the `zmq` crate as a dependency, which is a wrapper around the C ZeroMQ library. And when I build my `cxx` project as `staticlib`, the underlying `libzmq.a` static library is not linked into it. I have to then manually link it in my CMakeLists.txt file, which means that I need ZeroMQ to be present in the system in a place where CMake can find it. In the end, it makes building the entire project more complicated that it could be.

Would you say this is an issue with building `staticlib` crates in general, with the `zmq` crate or `cxx`?

**Comment by dtolnay** [comment]
If you'd like to avoid relying on ZeroMQ to be present in the system in a place where CMake can find it, the zmq crate's `vendored` feature appears relevant. https://github.com/erickt/rust-zmq/blob/eede4315e10eccddec4348561c42ded534e6001e/Cargo.toml#L28
It appears to build libzmq into the cargo-produced staticlib using https://github.com/jean-airoldie/zeromq-src-rs.

Generally I think what you're seeing go wrong is that the staticlib you are handing off from Cargo to CMake is not the only output artifact that Cargo produces. There is a lot of metadata along with it like linker flags, which are collected by Cargo from the output of [build scripts](https://doc.rust-lang.org/cargo/reference/build-scripts.html) in the transitive dependency graph. Unfortunately Cargo only records all of that information in a way that is only intended to be consumed by Cargo.

Based on what I've seen from the experience of people using CMake, this workflow of trying to mix Cargo and CMake is going to be super annoying for anything beyond very basic crates. If it's an option for you, it could be worth exploring something like Bazel which natively handles mixed-language projects extremely well.

Otherwise I would recommend pursuing how to connect the rest of Cargo's output metadata to CMake. Likely requires Cargo changes.

**Comment by mindv0rtex** [comment]
Hmm, when you say "requires Cargo changes", do you mean changing its source code? Then it's definitely more than I can handle.

**Comment by mindv0rtex** [comment]
After reading your comment I decided to check all the cargo output artifacts and there's indeed the static ZeroMQ lib stored in one of the folders. I'm gonna try a brute force approach and just look for it recursively from CMake.

**Comment by mindv0rtex** [comment]
Just letting anyone who might possibly find this useful, my crude solution works good enough. I basically just glob the cargo build folder for the library filename inside my CMake file and link it to my C++ executable.
