### ISSUE TITLE
[already solved] a confusing compiler error due to missing dependency on cxx

### ISSUE THREAD

**Issue by oconnor663** [dtolnay/cxx#680]
I set up a project called `test_harness` to exercise some C++ code, and early on I ran into a confusing compiler error:

```
   Compiling test_harness v0.0.0 (/home/jacko/chunked_aes/cpp/test_harness)
error: couldn't read src/test_harness/root/cpp/chunked_aes.hpp: No such file or directory (os error 2)
 --> src/lib.rs:4:9
  |
4 |         include!("test_harness/root/cpp/chunked_aes.hpp");
  |         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  |
  = note: this error originates in a macro (in Nightly builds, run with -Z macro-backtrace for more info)
```

In this case `test_harness/root/cpp/chunked_aes.hpp` definitely exists. And I see that rustc is trying to read `src/test_harness/...`, which is weird. (`src` shouldn't be there.)

It turns out that the cause of this is that I was missing the direct dependency on `cxx`. I only had the build dependency on `cxx-build`. Apparently this causes rustc to skip right over the `#[cxx::bridge]` directive and try to interpret the `include!` macro, leading to this super confusing error.

The core lesson here is "stop randomly skipping around in docs Jack", but anyway I thought I'd post this in case anyone else is doing a text search for the same issue. Thanks for making this crate!

**Comment by jfirebaugh** [comment]
For anyone else who ends up here trying to diagnose a "No such file or directory" error on the `include!` line, what finally allowed me to figure out what was happening was to _comment out_ the `include!` line. Then rustc will emit errors that will allow you to diagnose why the `#[cxx::bridge]` directive can't be resolved (for me it was because there were duplicate cxx crates available due to some BUILD.bazel misconfiguration).
