### ISSUE TITLE
Box<u32> not supported in shared structs

### ISSUE THREAD

**Issue by jrmuizel** [dtolnay/cxx#686]
I get:
```
  error[cxxbridge]: unsupported target type of Box
    ┌─ src/main.rs:9:22
    │
  9 │                   c: Box<Vec<u32>>,
    │                      ^^^^^^^^^^^^^ unsupported target type of Box
```

**Comment by dtolnay** [comment]
Do you mean `Box<Vec<u32>>` or `Box<u32>`? Subject is latter, your error shows former.

Can you explain more why you need whichever type, as opposed to `Vec<u32>` or `u32`?

**Comment by jrmuizel** [comment]
Ah sorry, I meant to paste the error for `Box<u32>`. That being said, `Box<Vec<u32>>` doesn't work either.

I don't actually have I use case for either type, I was just experimenting to see what `cxx` all supports.

**Comment by dtolnay** [comment]
I would prefer not to change this then if there isn't a use case. There shouldn't be any reason to use those types.

**Comment by thomasantony** [comment]
@dtolnay I recently had a use-case for `Box<Vec<u8>>`. I was wrapping a C++ library that takes ownership of a u8 array passed into it and casts it into a unique_ptr. The API allowed for defining a custom "free_fn" for the `unique_ptr`. Since this was something that was called frequently I was trying to make it zero-copy. What I ended up doing was defining this as a shared struct:

```
#[derive(Debug)]
    pub struct ByteVec{
        inner: Vec<u8>
    }
```
Defining this "extern rust" function:
```
fn get_vec(bv: &ffi::ByteVec) -> &Vec<u8>
{
    &bv.inner
}
```

And then in the C++ wrapper, I would pass in a Box<ByteVec> and do something like the following:

```
void api_fn_wrapper(rust::Box<ByteVec> data_vec)
{
    auto box_ptr = data_vec.into_raw();
    auto rust_vec = get_vec(*box_ptr);
    
    const auto num_bytes = rust_vec.size();
    const auto msg_bytes = rust_vec.data();
    /// The second argument to free_fn, "box_ptr" is a "context" value that the API I am wrapping allows
    auto free_fn = [](uint8_t* ptr, void* box_ptr)
    {
        RustBoxVec boxed_value = RustBoxVec::from_raw((ByteVec*)box_ptr); 
    };

    my_api_fn(msg_bytes, num_bytes, free_fn, (void*) box_ptr);
}
```

This would have been a little less convoluted if `Vec<u8>` was allowed inside `Box`.
