### ISSUE TITLE
Failing to link an integration test 

### ISSUE THREAD

**Issue by alexeyr** [dtolnay/cxx#702]
I've tried to change a test from using `#[test]` to a separate binary without test harness as you can see [here](https://github.com/alexeyr/tokenizers/commit/ca69c2f7b2194957b68012050e8dc409acf54f88). But this change produces an error:

```
E:\MyProgramming\tokenizers\bindings\cpp [no-test-harness ≡]> cargo test --features=test
   Compiling tokenizers-cpp v0.1.0 (E:\MyProgramming\tokenizers\bindings\cpp)
error: linking with `link.exe` failed: exit code: 1120
  |
  = note: "E:\\VisualStudio\\VC\\Tools\\MSVC\\14.26.28801\\bin\\HostX64\\x64\\link.exe" "/NOLOGO" "/NXCOMPAT" "/LIBPATH:E:\\Rust\\.rustup\\toolchains\\stable-x86_64-pc-windows-msvc\\lib\\rustlib\\x86_64-pc-windows-msvc\\lib" "E:\\MyProgramming\\tokenizers\\bindings\\cpp\\target\\debug\\deps\\cpp_doctest-c13fe2a19cdebc6d.122k2ey402kitdea.rcgu.o" 
<large number of arguments omitted>
"advapi32.lib" "ws2_32.lib" "userenv.lib" "msvcrt.lib"
  = note: cpp_doctest-c13fe2a19cdebc6d.ru2wy9o9w9kow63.rcgu.o : error LNK2019: unresolved external symbol huggingface$tokenizers$cxxbridge1$run_tests referenced in function _ZN11cpp_doctest3ffi9run_tests17h49e7caaaae4c0027E
          E:\MyProgramming\tokenizers\bindings\cpp\target\debug\deps\cpp_doctest-c13fe2a19cdebc6d.exe : fatal error LNK1120: 1 unresolved externals
```

As far as I understand, `tests.rs.cc` should still be built and linked by [the build script](https://github.com/alexeyr/tokenizers/blob/90db3fd41f2b58c6e84a14c2d9fc228193e9fa94/bindings/cpp/build.rs), and it's the one which contains
```
extern "C" {
bool huggingface$tokenizers$cxxbridge1$run_tests(::rust::Str data_dir, ::rust::Slice<::rust::String> cli_args) noexcept {
  bool (*run_tests$)(::rust::Str, ::rust::Slice<::rust::String>) = ::huggingface::tokenizers::run_tests;
  return run_tests$(data_dir, cli_args);
}
} // extern "C"
```

What am I missing?

**Comment by dtolnay** [comment]
This is because you have the Rust side of the bridge and the C++ side of the same bridge not in the same crate. Both sides are required to be in the same crate.

Every integration test is treated by Cargo as if it were a totally separate crate (see https://doc.rust-lang.org/cargo/reference/cargo-targets.html#integration-tests) downstream of the library crate. You used to have the C++ side and Rust side both in the `tokenizers` crate which works, but the commit you linked moves the Rust side into one of the integration test crates and keeps the C++ side in the `tokenizers` crate's build.rs.

I don't think Cargo currently supports build.rs for integration tests so you would need to figure out some other structure here.

**Comment by alexeyr** [comment]
> I don't think Cargo currently supports build.rs for integration tests so you would need to figure out some other structure here.

All right, thank you. I'll just keep what I had for now.

**Comment by alexeyr** [comment]
Though, how does cxx build its own integration tests? I just assumed it was in `build.rs`, but as you point out it isn't.

**Comment by dtolnay** [comment]
The C++ side of the bridge and the Rust side are in the same crate. See https://github.com/dtolnay/cxx/tree/1.0.29/tests/ffi.
