### ISSUE TITLE
Code is recompiled each time

### ISSUE THREAD

**Issue by vertrex** [dtolnay/cxx#730]
Hi, 

I use CXX in one of my crate and an other depends of it. Each time I run cargo build or cargo run, my c++ code is recompiled even if there is no change in any file. I tried to use  println!("cargo:rerun-if-changed/") but I didn't change anything, must I print for each of the file (I have lot of c++ and header file in sub dir)  ? 

Tahnk you

**Comment by adetaylor** [comment]
Maybe you could use something like [WalkDir](https://docs.rs/walkdir/2.3.1/walkdir/) to output the `cargo:rerun-if-changed` string for each C++/header file?

I think this is all largely beyond the control of the `cxx` crate, since we just use [cc](https://docs.rs/cc/1.0.67/cc/) for our Cargo C++ build.

**Comment by dtolnay** [comment]
@vertrex can you provide a minimal repro of this? Ideally the best would be a repo I can check out and run `cargo build && cargo build` and observe it build two times.

**Comment by vertrex** [comment]
It worked after adding : 

```

    let paths = fs::read_dir("./").unwrap();
    for path in paths { println!("cargo:rerun-if-change={}", path.unwrap().path().display()) }
```

Thank you

**Comment by dtolnay** [comment]
Closing as very likely a consequence of this misbehavior/bug in Cargo: https://github.com/rust-lang/cargo/issues/6003.
