### ISSUE TITLE
Allow safe functions with raw pointer arguments

### ISSUE THREAD

**Issue by Plecra** [dtolnay/cxx#755]
With the current implementation, it looks like raw pointer arguments force functions to be marked unsafe. This arbitrarily restricts patterns that don't need to `unsafe`ly use the pointers.

```rust
extern "Rust" {
    fn log_address(ptr: *const ());
}
fn log_address(ptr: *const ()) {
    eprintln!("{:p}", ptr);
}
// A more realistic might be a datastructure that holds erased types. Either way, the Rust code
// shouldn't be `unsafe` if it isn't performing unsafe operations
```

If there *are* any `unsafe` blocks within the function (which would be necessary to dereference them), then Rust has always made it the developer's responsibility to document the invariants. I see no reason for this to be different in `cxx`, and the inconsistency implies that there's something `unsafe` about even passing pointers to a function in the first place.

**Comment by adetaylor** [comment]
See https://github.com/dtolnay/cxx/issues/164#issue-608611434 for dtolnay@'s comment which proposed this.

My opinion (as #689 was initially my work):
* For `extern "C++"` blocks I think it's absolutely right that functions with pointer arguments are marked `unsafe`. Using a C++ function is _likely_ to dereference the pointer, `cxx` can't know for sure, and it's right that code calling such functions has to think carefully about the pointer they're passing in.
* For `extern "Rust"` blocks I agree with you. The Rust implementation of the function can have certain parts of the function potentially marked `unsafe` if it chooses to dereference the pointer, and otherwise, it shouldn't need to be `unsafe`. Even if we assume that 99% of such functions will dereference the pointer, it's nevertheless safer for specific parts of those functions to be marked as `unsafe` rather than the whole function. And marking it as `unsafe` doesn't make any difference to how it's called from C++ anyway.

We will need to wait to see what @dtolnay says but if he agrees with you for `extern "Rust"` functions, I'd be happy to be involved in reviewing a PR to relax this restriction on `extern "Rust"` functions.

**Comment by dtolnay** [comment]
I would prefer not to change this. FYI the implementation of the function does not need to be an unsafe fn, only the declaration in the bridge module. So you are still free to use internal unsafe blocks to delimit parts of the implementation which rely on the validity of the pointer, if any.
