### ISSUE TITLE
[Question] Create a CxxVector in Rust to return it to C++?

### ISSUE THREAD

**Issue by Geobert** [dtolnay/cxx#756]
Hi,

thank you for this project, it is very very promising!

I'd like to return a `CxxVector<u8>` back to C++ from a Rust function, but can't see how to create a `CxxVector` in the first place.

```rust
#[cxx::bridge]
mod ffi {
    fn build() -> Result<CxxVector<u8>>;
}
```

What am I missing?

**Comment by mikhailzagurskiy** [comment]
To do that, you should allocate some memory on the heap for the CxxVector content, then move it from the rust to the c++. Unfortunately, you can't do it straightforward, because CxxVector isn't trivially move constractible.
But you don't have to return CxxVector - just return rust::Vec, and then convert it to the CxxVector inside C++.
Simplifying my advice: return by value only language-specific types, and then convert it to the target language type inside the target language files.

For example:

```
 In Rust:
Create Vec<T>  =>  Pass it as Vec<T> to C++

In C++:
Get rust::Vec from Rust => Convert it by std::copy or std::transform to std::vector<T> => Use it
```

**Comment by dtolnay** [comment]
Hi @Geobert, `Result<CxxVector<u8>>` is not a type that you can possibly have in Rust, because std::vector has a move constructor and possibly internal pointers which are incompatible with how Rust does move semantics. You would need to use one of:

1. `fn build(out: Pin<&mut CxxVector<u8>>) -> Result<()>;` with a stack-allocated empty vector constructed by C++ for Rust to write the elements into, which is pinned and never moved by Rust

2. `fn build() -> Result<UniquePtr<CxxVector<u8>>>;` with a heap-allocated vector which you obtain in Rust via a call to an `extern "C++"` helper function that creates an empty `UniquePtr<CxxVector<u8>>` in C++ for Rust to fill and return back

3. `fn build() -> Result<Vec<u8>>;` using the Rust vector instead, which does not have internal pointers and so can be moved normally in Rust

**Comment by Geobert** [comment]
I understand, thank you both!
