### ISSUE TITLE
[Question] Exposing builder pattern and issue with lifetime

### ISSUE THREAD

**Issue by Geobert** [dtolnay/cxx#770]
Hi, 

I have in Rust a builder pattern:
```rust
struct MyBuilder<'a> {
  // multiple fields , some with lifetime
}

impl<'a> MyBuilder<'a> {
  pub fn new() -> Self { 
    MyBuilder { 
       // all fields to None
    }
  }

  pub fn param1(self, param1: TypeOfParam1) -> Self {
     // ...
  }

  pub fn param2(self, param2: &'a TypeOfParam2) -> Self {
    // ...
  }

  pub fn build(self) -> BuiltType {}
}
```

I tried exposing this to C++ like this:
```rust
#[cxx::bridge]
mod ffi {
    extern "Rust" {
        type MyBuilder;

        unsafe fn new_builder<'a>() -> Box<MyBuilder<'a>>;

        unsafe fn param1<'a>(
            builder: Box<MyBuilder<'a>>,
            param1: &CxxString,
        ) -> Result<Box<MyBuilder<'a>>>;

        unsafe fn param2<'a>(
            builder: Box<MyBuilder<'a>>,
            param2: &'a CxxVector<u8>,
        ) -> Result<Box<MyBuilder<'a>>>;

        unsafe fn build<'a>(
            builder: Box<MyBuilder<'a>>,
        ) -> Result<Vec<u8>>;
    }
}
```

But had issue with param2 because of the lifetime.

So I went for:

```rust
#[cxx::bridge]
mod ffi {
    extern "Rust" {
        type MyBuilder;

        unsafe fn new_builder<'a>() -> Box<MyBuilder<'a>>;

        unsafe fn param1<'a>(
            builder: Box<MyBuilder<'a>>,
            param1: &CxxString,
        ) -> Result<Box<MyBuilder<'a>>>;

        unsafe fn build<'a>(
            builder: Box<MyBuilder<'a>>,
            param2: &Vec<u8>,
        ) -> Result<Vec<u8>>;
    }
}
```

This work because I'm lucky and only have one param that have a lifetime bound.

The other thing that is bothering me is passing the Box around, I need to create a new Box on each param call as by builder function are `fn param(self) -> Self`.

Which force C++ to call `std::move(builder)` on each param call as well (but I'm not sure this is avoidable).

Am I right doing so, or am I missing a cleaner solution?

**Comment by dtolnay** [comment]
Regarding lifetimes, I was not able to reproduce whatever error you would have seen. I would likely need you to provide a compilable repro (which I can ideally just clone from git and run `cargo check`) in order to be helpful. Here is what I wrote, which is exactly what you gave with only the missing type definitions and function bodies filled in: https://gist.github.com/rust-play/67ecc156b1e7a2892a11cf7255869228.

As for the boxing and std::move -- this is just a reflection that C++ has no good equivalent to Rust self-by-value method calls. My recommendation would be to wrap your original self-by-value builder into a self-by-reference builder, and expose only the self-by-reference one to C++. That API would become straightforward ordinary method calls in C++. Also only a single Box needs to be made.

Something like:

```rust
use std::mem;

type MyBuilderRs<'a> = self::MyBuilder<'a>;

#[cxx::bridge]
mod ffi {
    struct MyBuilder<'a> {
        rs: Box<MyBuilderRs<'a>>,
    }

    extern "Rust" {
        type MyBuilderRs<'a>;

        unsafe fn new_builder<'a>() -> MyBuilder<'a>;

        unsafe fn param1<'b, 'a>(
            self: &'b mut MyBuilder<'a>,
            param1: &CxxString,
        ) -> Result<&'b mut MyBuilder<'a>>;

        unsafe fn param2<'b, 'a>(
            self: &'b mut MyBuilder<'a>,
            param2: &'a CxxVector<u8>,
        ) -> Result<&'b mut MyBuilder<'a>>;

        unsafe fn build(self: &mut MyBuilder) -> Result<Vec<u8>>;
    }
}

impl<'a> Default for MyBuilder<'a> {
    fn default() -> Self {
        MyBuilder::new()
    }
}

fn new_builder<'a>() -> ffi::MyBuilder<'a> {
    let rs = Box::new(MyBuilder::new());
    ffi::MyBuilder { rs }
}

impl<'a> ffi::MyBuilder<'a> {
    fn param1(&mut self, param1: &CxxString) -> Result<&mut Self> {
        *self.rs = mem::take(self.rs.as_mut()).param1(param1);
        Ok(self)
    }

    fn param2(&mut self, param2: &'a CxxVector<u8>) -> Result<&mut Self> {
        *self.rs = mem::take(self.rs.as_mut()).param2(param2);
        Ok(self)
    }

    fn build(&mut self) -> Result<Vec<u8>> {
        Ok(mem::take(self.rs.as_mut()).build())
    }
}
```

Full compilable version: https://gist.github.com/rust-play/b38f01c8e63ab29aef3451f4606bac87

(Make sure you are using at least cxx 1.0.39 and cxx-build 1.0.39 for this, since the most recent releases have some fixes related to the use of explicit lifetime annotations.)

**Comment by Geobert** [comment]
What is that:
```rust
type MyBuilderRs<'a> = self::MyBuilder<'a>;
```

I'm discovering something new in Rust here :D

**Comment by Geobert** [comment]
(I was off last week hence the late answer):
Re the lifetime issue: It's because I need to transform the `Vec<u8>` into a type that doesn't belongs to me and don't have anything to construct it with a tie to a lifetime (https://docs.rs/picky/6.2.0/picky/key/struct.PrivateKey.html) So I guess until we got that, I can't get out of this lifetime issue (I think, or maybe there's another Rust pattern that I don't know of)
