### ISSUE TITLE
Create a way to add C++ attributes to generated classes or functions

### ISSUE THREAD

**Issue by sbrocket** [dtolnay/cxx#872]
It would be useful to me to be able to add the `[[nodiscard]]` attribute to certain generated types, like for Result-like types. Could we add a new Rust attribute that will cause the C++ codegen side to add the given attribute to a type or function declaration, for example `#[cxx_attribute="[[nodiscard]]"]`?

One caveat to a general "apply any C++ attribute" Rust attribute is that I'm uncertain whether any C++ attributes exist that might change the behavior of a type or function in ways that would violate CXX's expectations.

**Comment by dtolnay** [comment]
I'll close this since I don't think I would want to do an arbitrary-purpose "paste this blob into the generated file" which is what `#[cxx_attribute="[[nodiscard]]"]` would imply.

I filed #930 to propose specifically doing `#[must_use]`⟶`[[nodiscard]]` and `#[must_use = "..."]`⟶`[[nodiscard("...")]]`.
