### ISSUE TITLE
Parallelising cxx internals - possible?

### ISSUE THREAD

**Issue by jon-chuang** [dtolnay/cxx#985]
I don’t like waiting as long as I have to for my builds, even with a the small surface area for my bridge so far; on the other hand I’m keen to dig a bit into cxx’s internals (though I’ve alr glimpsed some of this for allocators/destructors for smart pointers) and about implementing more functionality - maybe `std::tuple`/`rust::tuple`, `rust::Option`/`std::optional` would be nice, and this provides a good jumping off point to have the knowledge to do so. 

So I’d like to ask if anyone has any thoughts on how possible it would be to parallelize cxx, which seems to take 15-30s for my 100s of loc files…

related: https://github.com/dtolnay/cxx/pull/704

**Comment by jon-chuang** [comment]
An easy win could be to somehow propagate feature flags down to https://github.com/dtolnay/cxx/blob/master/BUILD so that `third-party:cc` is built with feature flag `cc/parallel`

**Comment by jon-chuang** [comment]
Looking at the Bazel dependencies, this doesn't seem to be the case... `cc` seems to be used exclusively for building the included/generated cpp files... correct me if I'm wrong @dtolnay ?

**Comment by dtolnay** [comment]
I suspect whatever you are measuring is compilation time of your C++ dependencies, not anything involving cxx. I tried running cxx on a module containing many thousand signatures, and that only takes tens of milliseconds, which is in line with what I would expect. I'll go ahead and close the issue since I don't think it's likely that cxx itself would benefit at all from parallelism.

> I don't really know how `cc` is used, since my understanding is that my cpp files are being built by the Bazel-managed toolchain

`cc` is not involved if you are using Bazel for your builds.
